from __future__ import annotations

import os
import re
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path, PurePosixPath

from client_layout import resolve_client_layout


MOD_NAME = "PersistentDirectConnectIP"


def _bundle_path() -> Path:
    if getattr(sys, "frozen", False):
        frozen = Path(sys.executable).resolve().parent.parent / "resources" / "PersistentDirectConnectIP-baseline.zip"
        if frozen.is_file():
            return frozen
    return Path(__file__).resolve().parent.parent / "resources" / "PersistentDirectConnectIP-baseline.zip"


def _safe_extract(archive: zipfile.ZipFile, destination: Path) -> None:
    root = destination.resolve()
    for member in archive.infolist():
        pure = PurePosixPath(member.filename.replace("\\", "/"))
        if pure.is_absolute() or ".." in pure.parts or not pure.parts:
            raise zipfile.BadZipFile(f"Unsafe PersistentDirectConnectIP path: {member.filename}")
        target = (destination / Path(*pure.parts)).resolve()
        if target != root and root not in target.parents:
            raise zipfile.BadZipFile(f"PersistentDirectConnectIP path escapes staging: {member.filename}")
    archive.extractall(destination)


def ensure_installed(selected_root: str | Path) -> dict:
    """Install the hidden functional mod; profile values are written separately."""
    layout = resolve_client_layout(selected_root)
    target = layout.ue4ss_mods_dir / MOD_NAME
    main = target / "Scripts" / "main.lua"
    if main.is_file() and (target / "enabled.txt").is_file():
        return {"ok": True, "installed": True, "changed": False, "path": str(target)}
    bundle = _bundle_path()
    if not bundle.is_file():
        raise FileNotFoundError("PersistentDirectConnectIP baseline is missing from launcher resources.")
    with tempfile.TemporaryDirectory(prefix="dws-direct-connect-") as temp_name:
        staged = Path(temp_name)
        with zipfile.ZipFile(bundle) as archive:
            _safe_extract(archive, staged)
        source = staged / MOD_NAME
        if not (source / "Scripts" / "main.lua").is_file():
            raise RuntimeError("PersistentDirectConnectIP baseline failed validation.")
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(source, target, dirs_exist_ok=True)
    (target / "enabled.txt").write_text("", encoding="utf-8")
    return {"ok": True, "installed": True, "changed": True, "path": str(target)}


def _lua_string(value: str, maximum: int) -> str:
    clean = str(value or "")[:maximum]
    return '"' + clean.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "").replace("\n", "") + '"'


def write_profile_config(selected_root: str | Path, *, address: str = "", password: str = "",
                         server_type: str = "normal", enabled: bool = True) -> dict:
    """Atomically write the currently active World's private direct-link values."""
    installed = ensure_installed(selected_root)
    host = str(address or "").strip()[:300]
    if host and (any(ch.isspace() for ch in host) or not re.fullmatch(r"[A-Za-z0-9.:-]+", host)):
        raise ValueError("Direct Connect address contains unsupported characters.")
    mode = str(server_type or "normal").strip().casefold()
    if mode not in {"normal", "hardcore", "creative"}:
        mode = "normal"
    config = (
        "-- Generated by Dragonwilds Sync for the active World profile.\n"
        "-- Do not store this file in a shared mod archive.\n"
        "return {\n"
        f"    IP = {_lua_string(host if enabled else '', 300)},\n"
        f"    PASSWORD = {_lua_string(password if enabled else '', 512)},\n"
        f"    SERVER_TYPE = {_lua_string(mode, 16)},\n"
        f"    ENABLE_LAST_SERVER = {'true' if enabled and bool(host) else 'false'},\n"
        "    ENABLE_DIAGNOSTIC_LOG = false\n"
        "}\n"
    )
    path = Path(installed["path"]) / "Scripts" / "config.lua"
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix="config.", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(config); handle.flush()
            try: os.fsync(handle.fileno())
            except OSError: pass
        os.replace(temporary, path)
    finally:
        try: Path(temporary).unlink(missing_ok=True)
        except OSError: pass
    # Profile switching owns these values; stale fallback files would violate
    # that boundary and are therefore cleared every time config is materialized.
    for name in ("last_server.txt", "last_password.txt", "diagnostic.log"):
        try: (path.parent / name).unlink(missing_ok=True)
        except OSError: pass
    return {**installed, "configured": bool(enabled and host), "address": host if enabled else "",
            "server_type": mode, "password_written": bool(enabled and password)}


def clear_profile_config(selected_root: str | Path) -> dict:
    return write_profile_config(selected_root, enabled=False)
