const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('dragonwilds', {
  invoke: (method, params = {}) => ipcRenderer.invoke('dragonwilds:invoke', method, params),
  adminStatus: () => ipcRenderer.invoke('dragonwilds:admin-status'),
  restartAsAdmin: () => ipcRenderer.invoke('dragonwilds:restart-admin'),
  pickImage: () => ipcRenderer.invoke('dragonwilds:pick-image'),
  pickDirectory: () => ipcRenderer.invoke('dragonwilds:pick-directory'),
  pickExecutable: () => ipcRenderer.invoke('dragonwilds:pick-executable'),
  pickFile: (kind = 'all') => ipcRenderer.invoke('dragonwilds:pick-file', kind),
  filePath: (file) => { try { return webUtils.getPathForFile(file); } catch (_) { return ''; } },
  saveFile: (opts = {}) => ipcRenderer.invoke('dragonwilds:save-file', opts),
  createWorldShortcut: (data) => ipcRenderer.invoke('dragonwilds:create-world-shortcut', data),
  removeWorldShortcut: (name) => ipcRenderer.invoke('dragonwilds:remove-world-shortcut', name),
  backgroundSettings: (settings) => ipcRenderer.invoke('dragonwilds:background-settings', settings),
  notify: (event) => ipcRenderer.invoke('dragonwilds:notify', event),
  openMainWindow: () => ipcRenderer.invoke('dragonwilds:open-main-window'),
  openPath: (target) => ipcRenderer.invoke('dragonwilds:open-path', target),
  copyText: (text) => ipcRenderer.invoke('dragonwilds:copy-text', text),
  fileSha256: (target) => ipcRenderer.invoke('dragonwilds:file-sha256', target),
  openExternal: (target) => ipcRenderer.invoke('dragonwilds:open-external', target),
  openInAppBrowser: (target) => ipcRenderer.invoke('dragonwilds:open-in-app-browser', target),
  captureWebview: (payload = {}) => ipcRenderer.invoke('dragonwilds:capture-webview', payload),
  openManagedDialog: (payload = {}) => ipcRenderer.invoke('dragonwilds:managed-dialog-open', payload),
  managedDialogContent: (id) => ipcRenderer.invoke('dragonwilds:managed-dialog-content', id),
  managedDialogEvent: (payload = {}) => ipcRenderer.invoke('dragonwilds:managed-dialog-event', payload),
  updateManagedDialog: (payload = {}) => ipcRenderer.invoke('dragonwilds:managed-dialog-update', payload),
  closeManagedDialog: (id) => ipcRenderer.invoke('dragonwilds:managed-dialog-close', id),
  onManagedDialogEvent: (callback) => { if (typeof callback !== 'function') return () => {}; const fn=(_event,payload)=>callback(payload||{}); ipcRenderer.on('dragonwilds:managed-dialog-event',fn); return ()=>ipcRenderer.removeListener('dragonwilds:managed-dialog-event',fn); },
  onManagedDialogUpdate: (callback) => { if (typeof callback !== 'function') return () => {}; const fn=(_event,payload)=>callback(payload||{}); ipcRenderer.on('dragonwilds:managed-dialog-update',fn); return ()=>ipcRenderer.removeListener('dragonwilds:managed-dialog-update',fn); },
  onManagedDialogClosed: (callback) => { if (typeof callback !== 'function') return () => {}; const fn=(_event,payload)=>callback(payload||{}); ipcRenderer.on('dragonwilds:managed-dialog-closed',fn); return ()=>ipcRenderer.removeListener('dragonwilds:managed-dialog-closed',fn); },
  windowMinimize: () => ipcRenderer.invoke('dragonwilds:window-minimize'),
  windowToggleMaximize: () => ipcRenderer.invoke('dragonwilds:window-toggle-maximize'),
  windowClose: () => ipcRenderer.invoke('dragonwilds:window-close'),
  windowState: () => ipcRenderer.invoke('dragonwilds:window-state'),
  appUpdateMode: () => ipcRenderer.invoke('dragonwilds:app-update-mode'),
  appUpdateCheck: (opts = {}) => ipcRenderer.invoke('dragonwilds:app-update-check', opts),
  appUpdateApply: (opts = {}) => ipcRenderer.invoke('dragonwilds:app-update-apply', opts),
  appUpdateResult: () => ipcRenderer.invoke('dragonwilds:app-update-result'),
  appUpdateDismissResult: () => ipcRenderer.invoke('dragonwilds:app-update-dismiss-result'),
  rsdwWebviewPreload: () => ipcRenderer.invoke('dragonwilds:rsdw-webview-preload'),
  legalText: () => ipcRenderer.invoke('dragonwilds:legal-text'),
  configureRsdwToolkitRoot: (root) => ipcRenderer.invoke('dragonwilds:rsdw-toolkit-root', root),
  openDetachedWindow: (payload = {}) => ipcRenderer.invoke('dragonwilds:detached-open', payload),
  listDetachedWindows: () => ipcRenderer.invoke('dragonwilds:detached-list'),
  restoreDetachedWindow: (id) => ipcRenderer.invoke('dragonwilds:detached-restore', id),
  closeDetachedWindow: (id) => ipcRenderer.invoke('dragonwilds:detached-close', id),
  onDetachedWindowsChanged: (callback) => { if (typeof callback !== 'function') return () => {}; const fn=(_event,items)=>callback(items||[]); ipcRenderer.on('dragonwilds:detached-changed',fn); return ()=>ipcRenderer.removeListener('dragonwilds:detached-changed',fn); },
  onJoinRequest: (callback) => { if (typeof callback !== 'function') return () => {}; const fn=(_event,payload)=>callback(payload||{}); ipcRenderer.on('dragonwilds:join-request',fn); return ()=>ipcRenderer.removeListener('dragonwilds:join-request',fn); },
  nexusStatus: () => ipcRenderer.invoke('dragonwilds:nexus-status'),
  nexusConnectSSO: () => ipcRenderer.invoke('dragonwilds:nexus-connect-sso'),
  nexusConnectDevelopmentKey: (key) => ipcRenderer.invoke('dragonwilds:nexus-connect-dev-key', key),
  nexusDisconnect: () => ipcRenderer.invoke('dragonwilds:nexus-disconnect'),
  nexusSearch: (query) => ipcRenderer.invoke('dragonwilds:nexus-search', query),
  nexusMod: (modId) => ipcRenderer.invoke('dragonwilds:nexus-mod', modId),
  nexusFiles: (modId) => ipcRenderer.invoke('dragonwilds:nexus-files', modId),
  nexusDownloadDescriptor: (data) => ipcRenderer.invoke('dragonwilds:nexus-download-descriptor', data),
  nexusDownloadStage: (data) => ipcRenderer.invoke('dragonwilds:nexus-download-stage', data),
  nexusPrepareArchive: (target) => ipcRenderer.invoke('dragonwilds:nexus-prepare-archive', target),
  onNexusBrowserDownload: (callback) => { if (typeof callback !== 'function') return () => {}; const fn=(_event,payload)=>callback(payload||{}); ipcRenderer.on('dragonwilds:nexus-browser-download',fn); return ()=>ipcRenderer.removeListener('dragonwilds:nexus-browser-download',fn); },
  discordActivity: (activity) => ipcRenderer.invoke('dragonwilds:discord-activity', activity),
  discordClear: () => ipcRenderer.invoke('dragonwilds:discord-clear'),
  discordStatus: () => ipcRenderer.invoke('dragonwilds:discord-status'),
});
