#!/bin/sh
set -eu

export DRAGONWILDS_SYNC_APPDATA="${XDG_CONFIG_HOME:-$HOME/.config}/dragonwilds-sync"
export DRAGONWILDS_SYNC_URI_OPENER="xdg-open"
export DRAGONWILDS_STEAM_APP_ID="${DRAGONWILDS_STEAM_APP_ID:-1374490}"

if [ -d /home/dragonwilds/rs_server ]; then
  export DRAGONWILDS_SERVER_INSTALL_DIR="${DRAGONWILDS_SERVER_INSTALL_DIR:-/home/dragonwilds/rs_server}"
fi
if [ -d /home/dragonwilds/steamcmd ]; then
  export DRAGONWILDS_STEAMCMD_DIR="${DRAGONWILDS_STEAMCMD_DIR:-/home/dragonwilds/steamcmd}"
fi

exec zypak-wrapper /app/dragonwilds-sync/dragonwilds-sync-app "$@"
