window.DWSYNC_RELEASE_META = Object.freeze({
  version: '2.7.17',
  name: 'V2.7.17 · Accurate Mod Management',
  rsdwlVersion: 3,
  attributions: [
    ['Application Creator', 'Jonesing4Space'],
    ['RuneSchema', 'Snorkles'],
    ['RSDW', 'Hi im Tat'],
    ['RSDW Modding Community', 'Community contributors'],
  ],
  changelog: [{
    version: '2.7.17',
    title: 'Accurate Mod Management',
    items: [
      'Mod replacement warnings now compare gameplay payload only; server-push metadata, activation markers, and publication bookkeeping no longer create false alerts.',
      'Existing repository fingerprints migrate to the content-only format without marking every linked profile as changed.',
      'Mod Management adds instant in-memory search across mod names, types, sources, and linked Private World or Server profiles.',
      'Difference labels now explicitly say CONTENT DIFFERENCE so they are not confused with ordinary Sync publication updates.',
      'RSDWL profile exports keep connected Worlds, character saves, and presentation wrapped under their launcher profile while always excluding World passwords.',
      'Nested ExampleMod-style .rsdwl mod archives remain importable, and Mod Management can safely consolidate identity.txt plus hotload markers into one verified ID.txt.',
    ],
  }, {
    version: '2.7.16',
    title: 'Evergreen Sync & Interface Reliability',
    items: [
      'A running dedicated server continuously supervises and repairs its Sync broadcast and file-transfer service, including adopted server processes.',
      'Sync Settings and Directory Hosts remain available locally while remote Server Management stays in its own login workspace.',
      'DragonConnect is restored as hidden baseline infrastructure for both hosts and clients.',
      'The embedded WebGUI uses the official Sync visual language and built-in profiles use the full Sync icon, Dragonwilds icon, and default banner.',
      'Character Preview caps high-DPI WebGL pixel density to reduce GPU fragment work without changing saved character data or exports.',
    ],
  }, {
    version: '2.7.15',
    title: 'RuneSchema & Player Tracking Reliability',
    items: [
      'Custom RuneSchema flavors are verified by the installed native DLL hash and are no longer rewritten on every launch or publish.',
      'A loaded RuneSchema DLL is detected before any live runtime file is changed, preventing partial flavor installs.',
      'A locked optional flavor update is deferred while the last complete RuneSchema runtime remains launchable.',
      'Coordinate-bearing RSDWTools character rows are authoritative for player count and map tracking; unmatched log names remain account observations.',
      'Live player tracking resets across dedicated-server process and World changes so stale roster entries cannot leak between sessions.',
    ],
  }, {
    version: '2.7.14',
    title: 'Final Profile & Interface Cleanup',
    items: [
      'Custom RuneSchema flavors are rematerialized after runtime repair and displayed by their saved name on the active server profile.',
      'Remote Server Login lists every saved server profile and binds the session to its immutable profile ID.',
      'Quick Launch now scopes running and Sync state to the exact local, connected, co-op, or server profile.',
      'Character Studio centers its three tabs and keeps the 3D WebGL guest at full rendering priority.',
      'Settings uses a final coherent alignment layer and retired Microsoft Defender controls no longer appear.',
      'Helpy now provides subsystem screenshot galleries, refreshed captures, and .rsdwl-first nested-package guidance.',
      'Discord Rich Presence includes fuller route, profile type, player, health, timer, asset, and settings context.',
    ],
  }, {
    version: '2.7.13',
    title: 'Profile Runtime & Mod Import',
    items: [
      'Configuration now contains only game/server, UE4SS root, and RuneSchema root settings; child-mod files stay in Mod Management.',
      'Each hosted World can retain nameable custom RuneSchema core ZIP flavors and select them from its Configuration workspace.',
      'Manual mod import now opens a closable review dialog with automatic UE4SS, RuneSchema, and PAK structure detection plus an explicit override.',
      'Coordinate-bearing RSDW character telemetry is canonical and merges a coordinate-less Steam/log identity as an account alias.',
      'Ashenfall map tracking receives working default world bounds, and the item spawner no longer emits an unsupported private bridge command.',
      'World actions and update controls are consolidated, and DragonCore remains absent from baked defaults and packaged runtime archives.',
    ],
  }, {
    version: '2.7.12',
    title: 'Official RuneSchema Restoration',
    items: [
      'The Dragonwilds Sync launcher RuneSchema variant and its bundled archive have been removed.',
      'The first server start after updating restores one complete matched RuneSchema release from the original upstream GitHub repository.',
      'Official core DLL, configuration, support files, and enable marker are replaced together so mixed-version cores cannot survive.',
      'Separately installed RuneSchema child mods remain profile-owned and are preserved during the official restoration.',
      'Editable RuneSchema source URLs and the named launcher variant selector are removed; Restore / Update Official remains the standard path.',
      'An explicit manual override ZIP/drop target supports unreleased complete cores; launch preserves the override until Restore Official is selected.',
    ],
  }, {
    version: '2.7.11',
    title: 'Upstream UE4SS Marker Ownership',
    items: [
      'Dragonwilds Sync no longer replaces an existing RuneSchema enabled.txt during launch or variant selection.',
      'The original upstream marker is preserved byte-for-byte even when it is read-only.',
      'A blank marker is created only when enabled.txt is genuinely missing, matching the original UE4SS presence-marker behavior.',
      'RSDW Tools update opt-out follows the same rule and leaves its existing upstream enable marker untouched.',
    ],
  }, {
    version: '2.7.10',
    title: 'Base Runtime Update Controls',
    items: [
      'World settings explicitly select Official Base from the RuneSchema GitHub source or the Dragonwilds Sync Launcher Variant.',
      'RuneSchema and RSDW Tools remain enabled base mods; their new toggles control automatic updates only.',
      'Disabling RSDW Tools updates retains and self-enables the installed base mod without replacing its files during runtime repair.',
      'The chosen RuneSchema source and both update policies persist when World settings are reopened.',
    ],
  }, {
    version: '2.7.9',
    title: 'Game Password and Launch Recovery',
    items: [
      'DedicatedServer.ini now receives the decrypted gameplay and admin passwords; encrypted dws-secret references remain confined to Dragonwilds Sync profile storage.',
      'Launch verification resolves the same protected values and refuses to launch when a saved credential can no longer be recovered.',
      'RuneSchema variant activation atomically repairs a legacy read-only enabled.txt marker instead of failing server launch.',
      'RuneSchema runtime DLLs and its enable marker are excluded from World Configuration management, while the RuneSchema root config remains editable.',
    ],
  }, {
    version: '2.7.8',
    title: 'Dedicated Password and Route Retention',
    items: [
      'Server launch now hydrates both the install-root and nested RSDragonwilds DedicatedServer.ini trees so either executable layout receives the same WorldPassword and gameplay settings.',
      'Dedicated configuration verification rejects launch when any existing candidate INI copy disagrees and reports the stale paths explicitly.',
      'Blank LAN or Direct Connect refresh fields no longer erase a saved working route; intentional clearing uses an explicit cleared-routes operation.',
      'Direct Connect no longer sends an empty internal route when adding an externally queried World.',
      'Source-contract tests now inspect the active V2 renderer, Electron main process, and preload implementations instead of their compatibility shims.',
    ],
  }, {
    version: '2.7.7',
    title: 'Sync Recovery and RuneSchema Variants',
    items: [
      'Hosts can select the standard RuneSchema core or the extended persistence branch; the exact live core is distributed through the authenticated World Sync manifest while child mods remain profile-owned.',
      'DedicatedServer.ini writes are verified against the exact executable target before launch, including an exact WorldPassword readback without exposing the password.',
      'Connected World Details use the durable saved profile and missing routes recover from the last authenticated or advertised endpoint.',
      'Player save recovery is profile-bound: players approve once, changed assigned-character saves are retained separately from submissions, and only the same authenticated profile can restore its latest copy.',
      'An offered World-save snapshot is retained locally for conversion continuity, while player backups remain separate from the World save.',
      'Core Configuration is limited to collapsible game, UE4SS, and RuneSchema root sections with loader icons.',
    ],
  }, {
    version: '2.7.6',
    title: 'DragonConnect and Dedicated Identity Reliability',
    items: [
      'Connected World Details open the durable saved profile immediately and no longer require a currently reachable Sync route.',
      'DedicatedServer.ini updates preserve Dragonwilds-owned ServerGuid, roster, and future settings while replacing each managed gameplay value exactly once.',
      'The dedicated server can continue writing its own identity state because Dragonwilds Sync no longer marks DedicatedServer.ini read-only.',
      'DragonConnect 0.4.2 waits for the real password widget to finish construction, performs one bounded handoff, and stops repeatedly rewriting live fields.',
      'UE4SS diagnostics now identify the helper as DragonConnect and record the exact password widget used without logging the password.',
    ],
  }, {
    version: '2.7.5',
    title: 'Gameplay Password and Core Configuration Reliability',
    items: [
      'Saving an active hosted World now writes the canonical WorldPassword to every resolved DedicatedServer.ini target and restarts Dragonwilds so the running game process actually loads it.',
      'DragonConnect commits saved credentials through the live UMG SetText function and scans already-created password fields, preventing a password that looks filled but is not used by Join.',
      'Connected World Details now retain the backend-selected saved profile and enrich it with live metadata instead of discarding the selected profile state.',
      'Core Configuration now shows only server/player files plus UE4SS and RuneSchema root configuration; individual mod files remain in Mod Management.',
      'Incomplete LAN or Direct Connect refreshes can no longer erase a working profile route; retry also recovers from the last authenticated Sync endpoint.',
      'WebHost is now a focused Server Management login page with no manifest, preview, configuration tabs, or background directory polling.',
      'Hosting Focus is limited to the local running hosted profile and includes a dismiss control.',
      'LAN and Direct server-finder cards keep readable dark controls, and PAK, UE4SS, and RuneSchema badges filter the advertised inventory correctly.',
    ],
  }, {
    version: '2.7.4',
    title: 'Connected World and LAN Sync Reliability',
    items: [
      'LAN, Direct Connect, and manually added Worlds now open in a dedicated Connected Worlds tab and remain reachable after saving or a failed first Sync attempt.',
      'LAN authentication falls through to the ordinary empty-password challenge when LAN trust is unavailable, while hosts recognize clients across physical, VPN, Hyper-V, WSL, and other local interfaces.',
      'Sync HTTP transport defaults to TCP 27051 without changing legacy gameplay identity on UDP 7777, preventing portless Sync addresses from dialing the game port.',
      'DragonConnect can use Automatic, Public, or LAN routing per World so local players can bypass routers without NAT hairpin support.',
      'Character-viewer backdrops are decoded through a constrained Electron bridge and embedded safely into the remote viewer.',
    ],
  }, {
    version: '2.7.3',
    title: 'Durable World Discovery and Responsive Sync',
    items: [
      'LAN and Direct Connect now save one durable, fingerprint-deduplicated World profile before testing Sync, so an unreachable host or rejected password cannot make the profile disappear.',
      'Newly discovered profiles open under Direct Worlds with stale search and classification filters cleared, keeping the saved card immediately visible.',
      'Linux LAN browsing is read-only and no longer invokes privilege elevation or changes firewall rules during an ordinary scan.',
      'Heartbeat and directory refreshes use compact bounded batches without repeatedly transferring cached artwork, characters, or the complete application state.',
      'Automatic bulk presentation prefetching was removed; full World details load only when requested.',
      'Server Management remains visible inside Sync for setup and status instead of being hidden by a legacy compatibility layer.',
    ],
  }, {
    version: '2.7.2',
    title: 'Verified Direct Connect and Reliable World Sync',
    items: [
      'Direct Connect now queries the typed host on UDP 8422, presents matching Sync Worlds for selection, and uses the advertised TCP Sync endpoint for authenticated metadata and file transfer.',
      'World Password authentication uses the active hosted World authority, with a pinned-TLS password fallback and detailed safe diagnostics when challenge authentication fails.',
      'LAN Worlds support password-free local trust, selectable discovery results, profile/IP allowlisting and blocking, community-rule acceptance, and stable World fingerprints.',
      'Connected World saves and default profiles are deduplicated by verified identity so repeated discovery or connection does not create duplicate profiles.',
      'Quick Launch windows are movable and consistently laid out, with visible connection stages, heartbeat state, diagnostics export, and reliable child-process cleanup.',
      'Firewall, UPnP, router guidance, and connection information now distinguish game UDP 7777+, Sync transfer TCP 27051+, Direct Connect discovery UDP 8422, and optional WebHost TCP 27080.',
    ],
  }, {
    version: '2.7.1',
    title: 'Connected World Profile and Mod Broadcast Corrections',
    items: [
      'LAN and direct World saves are idempotent by verified fingerprint or exact World identity and endpoint, preventing duplicate connected profiles.',
      'Connected profiles retain complete PAK, UE4SS, and RuneSchema metadata through discovery, status checks, synchronization, and reloads.',
      'Placard framework badges open the exact advertised mod family while card flipping occurs only through explicit front/back controls.',
      'World Management includes the Manifest workspace and Local World selection presents populated save-backed profiles before creating a new profile.',
      'The dedicated Mods application uses its own clean repository workspace instead of the Settings navigation shell.',
    ],
  }, {
    version: '2.7.0',
    title: 'Verified Connections, Complete Mod Discovery, and Live Delta Sync Progress',
    items: [
      'One World Management workspace covers Singleplayer, Co-Op, dedicated, manifest, and favorited Worlds with clear mode/source banners, save discovery, conversion, Game Setup, and Server Setup.',
      'Vortex-style World profiles live under LocalAppData/DragonwildsSync/profiles/world and retain recoverable metadata, configuration, UE4SS/RuneSchema mods, PAKs, managed files, and activeworld identity for full profile exchange.',
      'Mod management supports UE4SS, RuneSchema, PAKs, optional Nexus provenance, drag-and-drop numbered load order, automatic mods.txt repair, canonical ID.txt metadata, rollback, and client synchronization.',
      'Settings → Mod Management provides one canonical UE4SS/RuneSchema/PAK repository across all Private Worlds and Server Profiles; explicit Publish & Push includes newly added schema/config files while preserving profile-specific enablement and order.',
      'Loaded Private Worlds and stopped hosted Worlds can be unloaded from their right-click menu: changes are snapshotted first, then World-owned files are cleared back to the shared runtime-core baseline.',
      'Nexus website downloads open inside an isolated application browser and completed ZIP/7z archives enter the same staging, conversion, inspection, backup, install, and provenance flow as authorized direct downloads.',
      'The built-in portable updater now defaults to the official gh0sted5456-us/Dragonwilds-Sync GitHub releases repository.',
      'Application Updates now exposes only Check for Updates and Update Application; the official repository is fixed internally and only the portable executable is replaced.',
      'World Management /Game and /Server now own editable directory and executable fields with direct validation instead of redirecting to removed Settings controls.',
      'Existing dedicated-server adoption detects UE4SS, RuneSchema, and nested PAK mod groups, asks before copying them into the selected World Profile, and correctly resolves official SteamCMD installs whose real game root is the nested RSDragonwilds directory.',
      'mods.txt and dwmapi.dll are hidden runtime/control infrastructure rather than distracting mod entries; a client-safe mods.txt is automatically pushed whenever a World presents UE4SS mods.',
      'Each server mod now has an always-visible Mod Mode selector; mode changes persist immediately without rescanning a remote server share and remain pending until the explicit Publish & Push action.',
      'Managed mods receive one editable ID.txt contract for identity, tags, runtime role, hotload capability, and custom items; legacy metadata remains readable.',
      'Resizable in-app windows now fill their resized frame and minimize reliably to the in-app taskbar.',
      'RSDW refreshes maintain an atomic full upstream icon manifest while custom item icon bindings remain preserved separately.',
      'The detachable Mod Explorer provides Edit, Copy, and confirmed Delete from each file context menu while keeping every operation inside the selected mod root.',
      'Live Config is limited to overarching World/Game, UE4SS core, and RuneSchema core settings; individual mod recipes and configuration remain in each mod Explorer.',
      'Character Studio now combines Combat Identity, character statistics, World associations, and every RSDW editor in one page; the troublesome embedded 3D viewport has been removed.',
      'Player Inventory uses standardized compact tabs, full-width Equipment and Action Bar rails, and a portable custom-item manifest with names, vanilla/custom icons, item and hand types, and stack limits.',
      'UE4SS, RuneSchema, and PAK packages can carry dragonwilds-sync-items.json or a .dwsync-items.json sidecar; Dragonwilds Sync discovers and merges those definitions without installing a runtime companion.',
      'Sync/WebHost rebroadcasts saved/imported manifests, directory results, public-list results, and hosted profiles; it deduplicates by verified fingerprint or normalized IP plus exact World Name.',
      'WebHost includes a responsive public directory, versioned API, authenticated Remote Server login, scoped users, CSRF-protected actions, audit history, and GitHub-ready OpenAPI documentation.',
      'World Management tabs paint cached content immediately, deduplicate in-flight requests, and refresh volatile player/map data separately from stable configuration.',
      'Hardware acceleration is enabled by default. Application settings can disable GPU composition for troubleshooting or set an Automatic, 1, 2, 4, or 8 GB renderer heap ceiling; both apply after restart.',
      'Windows releases are portable-only. Retired launcher-built gameplay helpers and their installer/update routes are no longer bundled.',
      'Linux AppImage, tarball, Flatpak, CI, and in-app Linux runtime controls remain outside V2; this release makes no Linux support claim.',
      'Kid-Friendly, Adults Only, Discord, Steam, Epic, Nintendo, PlayStation, Xbox, country, and language identifiers use packaged icon/flag artwork while connection attempts remain user-controlled.',
      'Creator and community recommendation feeds publish source links and metadata from GitHub-compatible JSON. No Nexus-hosted or other third-party mod archive is bundled or redistributed.',
      'All local, co-op, and dedicated Worlds can publish Community Rules through Sync manifests, the public directory/API, hosted website, remote portal, and exported profiles.',
      'A safe tilde command palette provides declared start/stop broadcast and server actions plus temporary Nexus integration visibility without exposing a shell.',
      'Safe resets preserve EOS/account data and back up saves/config/mods; profile writes, imports, network administration, and editable files use validation, bounded paths, and atomic updates.',
    ],
  }],
  licenseTitle: 'Dragonwilds Sync Community License 1.0',
  licenseSummary: 'Free-of-charge use, modification, mirroring, and redistribution are permitted with attribution. Dragonwilds Sync itself may not be sold or placed behind mandatory payment. The .rsdwl extension/specification is royalty-free and open for interoperability. Third-party materials remain under their owners\' terms.',
});
