(() => {
  'use strict';
  const api=window.dragonwilds;
  let cache=null, fetched=0, busy=false;
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function appState(force=false){if(!api?.invoke)return cache||{};if(!force&&cache&&Date.now()-fetched<3000)return cache;try{cache=await api.invoke('state.get',{});fetched=Date.now()}catch(_){}return cache||{}}
  function renameCommunity(root=document){const button=root.querySelector('[data-settings-tab="integrations"]');if(button){[...button.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).forEach(n=>{if(/integrations/i.test(n.textContent||''))n.textContent=(n.textContent||'').replace(/Integrations/ig,'Community')});button.querySelectorAll('span,strong,div').forEach(n=>{if(/^integrations$/i.test((n.textContent||'').trim()))n.textContent='Community'});button.title='Community';button.setAttribute('aria-label','Community')}}
  function retireHeavyWindows(root=document){root.querySelectorAll('[id^="detach-"],[data-detach-route],[data-open-detached]').forEach(n=>n.classList.add('rc2-retired'));root.querySelectorAll('button').forEach(n=>{if(/^open in window$/i.test((n.textContent||'').trim()))n.classList.add('rc2-retired')})}
  function removeDefender(root=document){root.querySelectorAll('section,.settings-section,.identity-box,.detail-section').forEach(section=>{const text=(section.textContent||'').toLowerCase();if(text.includes('microsoft defender')||/^\s*(server|client) defender\b/.test(text))section.classList.add('rc2-retired')})}
  function singleGithubChangelog(root=document){root.querySelectorAll('.settings-section').forEach(section=>{if(section.id==='github-release-changelog')return;const h=[...section.querySelectorAll('h2,h3')].find(x=>/^changelog$/i.test((x.textContent||'').trim()));if(h)section.classList.add('rc2-retired')})}
  async function openRouter(event){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();try{const r=await api.invoke('network.default_router',{});if(r?.url)await api.openExternal(r.url)}catch(e){alert(`Default router could not be opened: ${e.message||e}`)}}
  function fixRouter(root=document){root.querySelectorAll('[data-router-home],a[href*="unifi.ui.com"],button[data-open-external*="unifi.ui.com"]').forEach(node=>{node.textContent='Open Default Router Homepage';node.removeAttribute('data-open-external');node.removeAttribute('href');if(node.dataset.rc2Router!=='1'){node.dataset.rc2Router='1';node.addEventListener('click',openRouter,true)}})}
  function combineServerManagement(root=document){const settings=root.querySelector('[data-webhost-tab="settings"]');if(settings)settings.textContent='Website, Networking & Remote Access';root.querySelectorAll('[data-webhost-tab="remote"]').forEach(b=>b.classList.add('rc2-retired'));const panel=[...root.querySelectorAll('.webhost-authority')].find(n=>/server users/i.test(n.querySelector('h3')?.textContent||''));if(panel){const h=panel.querySelector('h3');if(h)h.textContent='Remote Users & Permissions';const add=panel.querySelector('#add-webhost-user');if(add){add.textContent='+ Add Remote User';add.title='Create credentials and assign permissions for one hosted World'}const section=panel.closest('.settings-section');if(section&&!section.querySelector('.rc2-remote-jump')){const jump=document.createElement('div');jump.className='rc2-remote-jump';jump.innerHTML='<button class="btn primary compact-btn" data-jump-remote-users>Manage Remote Users & Permissions</button>';section.insertBefore(jump,section.children[1]||null);jump.querySelector('button').onclick=()=>panel.scrollIntoView({behavior:'smooth',block:'start'})}}}
  function allWorlds(s){return [...(s?.client?.worlds||[]),...(s?.client?.discovered_worlds||[]),...(s?.client?.directory_worlds||[]),...(s?.client?.private_worlds||[]),...(s?.server_profiles||[])]}
  async function annotateCommunities(root=document){const cards=[...root.querySelectorAll('[data-world-id]')].filter(c=>!c.dataset.rc2Communities);if(!cards.length)return;const s=await appState();const map=new Map(allWorlds(s).map(w=>[String(w.id||''),w]));cards.forEach(card=>{card.dataset.rc2Communities='1';const world=map.get(String(card.dataset.worldId||''));const sources=world?.public_discovery?.directory_sources||world?.directory_sources||[];if(!sources.length)return;const host=card.querySelector('.world-tag-row,.tag-groups,.world-badges,.world-list-tags,.world-copy')||card;const chips=document.createElement('span');chips.className='community-source-chips';chips.title='Community lists that shared this same verified World';chips.innerHTML=sources.slice(0,2).map(x=>`<span class="community-source-chip">${esc(x.name||'Community')}</span>`).join('')+(sources.length>2?`<span class="community-source-chip">+${sources.length-2}</span>`:'');host.appendChild(chips)})}
  async function renderCommunity(root=document){const active=root.querySelector('[data-settings-tab="integrations"].active');if(!active)return;const note=root.querySelector('.settings-page-note');const page=note?.parentElement;if(!page||page.querySelector('#rc2-community'))return;const s=await appState(true);const rows=s?.application?.communities||[];[...page.children].forEach(child=>{if(child!==note&&!child.classList.contains('settings-subnav'))child.classList.add('rc2-retired')});const section=document.createElement('section');section.id='rc2-community';section.className='settings-section';const list=rows.length?rows.map(row=>`<div class="rc2-community-row" data-community-id="${esc(row.id)}"><div><strong>${esc(row.name||'Community')}</strong><small>${row.worlds_url?'World list · ':''}${row.recommendations_url?'Recommended Mods · ':''}${row.website_url?'Website':''}</small><small>${esc(row.worlds_url||'')}${row.worlds_url&&row.recommendations_url?' · ':''}${esc(row.recommendations_url||'')}</small></div><div class="rc2-community-actions"><span class="status-pill ${row.enabled===false?'unknown':'online'}">${row.enabled===false?'PAUSED':'ENABLED'}</span><button class="btn ghost compact-btn" data-community-toggle="${esc(row.id)}">${row.enabled===false?'Enable':'Pause'}</button><button class="btn danger compact-btn" data-community-remove="${esc(row.id)}">Remove</button></div></div>`).join(''):'<div class="empty-state">No communities added yet. A community can contribute a World directory, Recommended Mods feed, or both.</div>';section.innerHTML=`<div class="panel-header"><div><h2>Community</h2><span class="panel-subtitle">Subscribe to communities you are part of. Their World directories are fingerprint-deduplicated; if several communities advertise the same World, Dragonwilds Sync shows one World with multiple community identifiers.</span></div><button class="btn primary" data-community-refresh>Refresh Community Content</button></div><div class="rc2-community-list">${list}</div><div class="rc2-community-form"><input class="field" data-community-name placeholder="Community name"><input class="field" data-community-worlds placeholder="World directory URL (optional)"><input class="field" data-community-mods placeholder="Recommended Mods JSON URL (optional)"><button class="btn primary" data-community-add>Add Community</button></div><div class="identity-box"><strong>Community subscriptions are data sources, not accounts</strong><p>They can supply public World listings and Recommended Mods. Dragonwilds Sync still verifies compatible World fingerprints and keeps duplicate community sightings attached to one World card.</p></div>`;page.appendChild(section);
    const save=async(next)=>{if(busy)return;busy=true;try{const out=await api.invoke('application.communities.settings',{communities:next});cache=out.state||cache;fetched=Date.now();await Promise.allSettled([api.invoke('application.recommended_mods.refresh',{}),api.invoke('world.directory.refresh',{})]);cache=null;section.remove();renderCommunity(root)}finally{busy=false}};
    section.querySelector('[data-community-add]').onclick=()=>{const name=section.querySelector('[data-community-name]').value.trim(),worlds=section.querySelector('[data-community-worlds]').value.trim(),mods=section.querySelector('[data-community-mods]').value.trim();if(!name||(!worlds&&!mods))return;save([...rows,{name,worlds_url:worlds,recommendations_url:mods,enabled:true}])};section.querySelectorAll('[data-community-remove]').forEach(b=>b.onclick=()=>save(rows.filter(r=>String(r.id)!==String(b.dataset.communityRemove))));section.querySelectorAll('[data-community-toggle]').forEach(b=>b.onclick=()=>save(rows.map(r=>String(r.id)===String(b.dataset.communityToggle)?{...r,enabled:r.enabled===false}:r)));section.querySelector('[data-community-refresh]').onclick=async()=>{await Promise.allSettled([api.invoke('application.recommended_mods.refresh',{}),api.invoke('world.directory.refresh',{})]);cache=null;section.remove();renderCommunity(root)}}
  function smoothIcons(root=document){root.querySelectorAll('.platform-logo,.platforms img').forEach(img=>{img.style.filter='none';img.style.background='transparent';img.style.border='0';img.style.boxShadow='none'})}
  function enhance(){renameCommunity();retireHeavyWindows();removeDefender();singleGithubChangelog();fixRouter();combineServerManagement();smoothIcons();void renderCommunity();void annotateCommunities()}
  let scheduled=false;const schedule=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhance()})};
  document.addEventListener('click',e=>{if(e.target.closest('[data-settings-tab],[data-route]')){cache=null;setTimeout(schedule,20)}},true);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
  new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});
})();
