window.DWSYNC_RELEASE_META = Object.freeze({
  version: '1.1.9',
  name: 'V1.1.9 · Portable Studio & WebHost',
  rsdwlVersion: 3,
  attributions: [
    ['Application Creator', 'Jonesing4Space'],
    ['RuneSchema', 'Snorkles'],
    ['RSDW', 'Hi im Tat'],
    ['RSDW Modding Community', 'Community contributors'],
  ],
  changelog: [{
    version: '1.1.9',
    title: 'Portable Studio, Faster Navigation, and Federated WebHost',
    items: [
      'One World Management workspace covers Singleplayer, Co-Op, dedicated, manifest, and favorited Worlds with clear mode/source banners, save discovery, conversion, Game Setup, and Server Setup.',
      'Vortex-style World profiles live under LocalAppData/DragonwildsSync/profiles/world and retain recoverable metadata, configuration, UE4SS/RuneSchema mods, PAKs, managed files, and activeworld identity for full profile exchange.',
      'Mod management supports UE4SS, RuneSchema, PAKs, optional Nexus provenance, drag-and-drop numbered load order, automatic mods.txt repair, hotload.txt, tags.txt, rollback, and client synchronization.',
      'Settings → Mod Management provides one canonical UE4SS/RuneSchema/PAK repository across all Private Worlds and Server Profiles; explicit Publish & Push includes newly added schema/config files while preserving profile-specific enablement and order.',
      'Loaded Private Worlds and stopped hosted Worlds can be unloaded from their right-click menu: changes are snapshotted first, then World-owned files are cleared back to the shared runtime-core baseline.',
      'Nexus website downloads open inside an isolated application browser and completed ZIP/7z archives enter the same staging, conversion, inspection, backup, install, and provenance flow as authorized direct downloads.',
      'The built-in portable updater now defaults to the official gh0sted5456-us/Dragonwilds-Sync GitHub releases repository.',
      'The detachable Mod Explorer provides Edit, Copy, and confirmed Delete from each file context menu while keeping every operation inside the selected mod root.',
      'Live Config is limited to overarching World/Game, UE4SS core, and RuneSchema core settings; individual mod recipes and configuration remain in each mod Explorer.',
      'Character Studio now drives the already-loaded local RSDWModel viewport directly as body, face, color, armour, cape, or held-item choices change; profile icons use contained artwork and RPG-style save statistics.',
      'Player Inventory uses standardized compact tabs, full-width Equipment and Action Bar rails, and a portable custom-item manifest with names, vanilla/custom icons, item and hand types, and stack limits.',
      'UE4SS, RuneSchema, and PAK packages can carry dragonwilds-sync-items.json or a .dwsync-items.json sidecar; Dragonwilds Sync discovers and merges those definitions without installing a runtime companion.',
      'Sync/WebHost rebroadcasts saved/imported manifests, directory results, public-list results, and hosted profiles; it deduplicates by verified fingerprint or normalized IP plus exact World Name.',
      'WebHost includes a responsive public directory, versioned API, authenticated Remote Server login, scoped users, CSRF-protected actions, audit history, and GitHub-ready OpenAPI documentation.',
      'World Management tabs paint cached content immediately, deduplicate in-flight requests, and refresh volatile player/map data separately from stable configuration.',
      'Hardware acceleration is enabled by default. Application settings can disable GPU composition for troubleshooting or set an Automatic, 1, 2, 4, or 8 GB renderer heap ceiling; both apply after restart.',
      'Windows releases are portable-only. Retired launcher-built gameplay helpers and their installer/update routes are no longer bundled.',
      'Kid-Friendly, Adults Only, Discord, Steam, Epic, Nintendo, PlayStation, Xbox, country, and language identifiers use packaged icon/flag artwork while connection attempts remain user-controlled.',
      'The original LootMenu 1.0.4 archive remains an optional recommended client/server mod. Live map position tracking can use a separately installed RSDW DevKit RSDWTools bridge; Sync does not bundle or install it.',
      'Safe resets preserve EOS/account data and back up saves/config/mods; profile writes, imports, network administration, and editable files use validation, bounded paths, and atomic updates.',
    ],
  }],
  licenseTitle: 'Dragonwilds Sync Community License 1.0',
  licenseSummary: 'Free-of-charge use, modification, mirroring, and redistribution are permitted with attribution. Dragonwilds Sync itself may not be sold or placed behind mandatory payment. The .rsdwl extension/specification is royalty-free and open for interoperability. Third-party materials remain under their owners\' terms.',
});
