(() => {
  'use strict';
  const params=new URLSearchParams(location.search);
  if(params.get('embed')==='1')document.documentElement.classList.add('helpy-embedded');
  const requestedTheme=params.get('theme');
  if(['dark','white','glass'].includes(requestedTheme)){document.documentElement.dataset.theme=requestedTheme;localStorage.setItem('dragonwilds-sync-theme',requestedTheme);}
  const root=location.pathname.includes('/website/')?'../help/':'help/';
  const esc=(value)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const imageUrl=(value)=>new URL(String(value||''),new URL(root,location.href)).href;
  const nav=document.querySelector('#helpy-nav'),article=document.querySelector('#helpy-article'),search=document.querySelector('#helpy-search'),mobileNav=document.querySelector('#helpy-mobile-nav');
  let manifest=null,selected='';
  const pages=()=>manifest?.pages||[];
  const searchable=(page)=>`${page.title} ${page.category} ${page.summary} ${page.intro} ${(page.keywords||[]).join(' ')} ${JSON.stringify(page.sections||[])}`.toLowerCase();
  const filteredPages=()=>{const query=search.value.trim().toLowerCase();return pages().filter((page)=>!query||searchable(page).includes(query));};
  function renderNav(){
    const filtered=filteredPages(),groups=new Map();
    filtered.forEach((page)=>{const category=page.category||'Guide';if(!groups.has(category))groups.set(category,[]);groups.get(category).push(page);});
    nav.innerHTML=[...groups].map(([category,items])=>`<section><h2>${esc(category)}</h2>${items.map((page)=>`<button type="button" class="${page.id===selected?'active':''}" data-helpy-page="${esc(page.id)}"><span>${esc(page.icon||'◇')}</span><div><strong>${esc(page.title)}</strong><small>${esc(page.summary)}</small></div></button>`).join('')}</section>`).join('')||'<div class="helpy-empty"><strong>No matching guide</strong><span>Try a feature name or the visible error text.</span></div>';
    nav.querySelectorAll('[data-helpy-page]').forEach((button)=>button.addEventListener('click',()=>select(button.dataset.helpyPage)));
    document.querySelector('#helpy-results').textContent=search.value?`${filtered.length} result${filtered.length===1?'':'s'}`:`${pages().length} guides`;
  }
  function sectionMarkup(section,index){const kind=section.kind||(/warning|never|do not|failed|blocked/i.test(`${section.title} ${section.body}`)?'warning':'standard');return `<section class="helpy-section" data-kind="${esc(kind)}"><div class="helpy-section-number">${String(index+1).padStart(2,'0')}</div><div><h3>${esc(section.title)}</h3>${section.body?`<p>${esc(section.body)}</p>`:''}${section.steps?.length?`<ol>${section.steps.map((step)=>`<li>${esc(step)}</li>`).join('')}</ol>`:''}</div></section>`;}
  function renderPage(page){
    const shots=(Array.isArray(page.images)&&page.images.length?page.images:(page.image?[{src:page.image,alt:page.image_alt||page.title}]:[])).map((row)=>typeof row==='string'?{src:row,alt:page.title}:row);
    const gallery=shots.length?`<section class="helpy-gallery" aria-label="Screenshots"><div class="helpy-gallery-head"><div><span>Visual walkthrough</span><strong>${shots.length} current view${shots.length===1?'':'s'}</strong></div><small>Select any image to inspect it full-size.</small></div><div class="helpy-shot-grid">${shots.map((shot,index)=>`<button class="helpy-article-shot" type="button" data-helpy-image="${esc(imageUrl(shot.src||''))}" data-helpy-alt="${esc(shot.alt||page.title)}"><img src="${esc(imageUrl(shot.src||''))}" alt="${esc(shot.alt||page.title)}" loading="${index?'lazy':'eager'}"><span><b>${String(index+1).padStart(2,'0')}</b>${esc(shot.label||shot.alt||page.title)}</span></button>`).join('')}</div></section>`:'';
    const index=pages().findIndex((row)=>row.id===page.id),previous=pages()[index-1],next=pages()[index+1];
    article.innerHTML=`<header class="helpy-article-header"><div class="helpy-breadcrumb"><span>Helpy</span><b>›</b><span>${esc(page.category||'Guide')}</span></div><div class="helpy-title-row"><div><h2>${esc(page.title)}</h2><p>${esc(page.intro||page.summary||'')}</p></div><button type="button" id="helpy-copy-link">Copy link</button></div><div class="helpy-meta"><span>${esc(page.audience||'Players & server operators')}</span><span>${esc(page.time||`${Math.max(2,(page.sections||[]).length*2)} min read`)}</span><span>${(page.sections||[]).length} sections</span></div></header>${page.callout?`<aside class="helpy-callout"><strong>${esc(page.callout.title||'Before you begin')}</strong><p>${esc(page.callout.body||'')}</p></aside>`:''}${gallery}<div class="helpy-section-list">${(page.sections||[]).map(sectionMarkup).join('')}</div>${page.tips?.length?`<aside class="helpy-tips"><strong>Good to know</strong><div>${page.tips.map((tip)=>`<span>${esc(tip)}</span>`).join('')}</div></aside>`:''}<nav class="helpy-pager">${previous?`<button data-helpy-page="${esc(previous.id)}"><span>← Previous</span><strong>${esc(previous.title)}</strong></button>`:'<span></span>'}${next?`<button data-helpy-page="${esc(next.id)}"><span>Next →</span><strong>${esc(next.title)}</strong></button>`:'<span></span>'}</nav>`;
    article.querySelectorAll('[data-helpy-page]').forEach((button)=>button.addEventListener('click',()=>select(button.dataset.helpyPage)));
    article.querySelectorAll('[data-helpy-image]').forEach((button)=>button.addEventListener('click',(event)=>{const dialog=document.querySelector('#helpy-image-dialog'),image=dialog.querySelector('img');image.src=event.currentTarget.dataset.helpyImage;image.alt=event.currentTarget.dataset.helpyAlt;dialog.querySelector('p').textContent=event.currentTarget.dataset.helpyAlt;dialog.showModal();}));
    article.querySelector('#helpy-copy-link')?.addEventListener('click',async(event)=>{try{await navigator.clipboard.writeText(location.href);event.currentTarget.textContent='Copied';setTimeout(()=>event.currentTarget.textContent='Copy link',1400);}catch(_){}});
  }
  function select(id,{scroll=true}={}){const page=pages().find((row)=>row.id===id)||pages()[0];if(!page)return;selected=page.id;history.replaceState(null,'',`${location.pathname}${location.search}#${encodeURIComponent(selected)}`);mobileNav.value=selected;renderNav();renderPage(page);if(scroll)document.querySelector('.helpy-layout')?.scrollIntoView({behavior:'smooth',block:'start'});}
  async function load(force=false){article.innerHTML='<div class="helpy-loading"><span class="status-dot"></span><strong>Loading current field guide…</strong></div>';try{const response=await fetch(`${root}manifest.json${force?`?v=${Date.now()}`:''}`,{cache:force?'reload':'default'});if(!response.ok)throw new Error(`Help source returned ${response.status}`);manifest=await response.json();if(manifest.schema!=='DragonwildsSync.Help.v1'||!Array.isArray(manifest.pages))throw new Error('Unsupported Helpy manifest');document.querySelector('#helpy-subtitle').textContent=manifest.subtitle||'';document.querySelector('#helpy-version').textContent=`Guide ${manifest.version} · updated ${manifest.updated_at||manifest.updated||'current release'}`;document.querySelector('#helpy-guide-count').textContent=pages().length;document.querySelector('#helpy-shot-count').textContent=pages().reduce((sum,page)=>sum+(page.images?.length||Number(!!page.image)),0);mobileNav.innerHTML=pages().map((page)=>`<option value="${esc(page.id)}">${esc(page.category)} · ${esc(page.title)}</option>`).join('');select(decodeURIComponent(location.hash.slice(1))||selected||pages()[0]?.id,{scroll:false});}catch(error){article.innerHTML=`<div class="helpy-error"><strong>Helpy could not load.</strong><p>${esc(error.message)} Refresh when GitHub Pages is available.</p></div>`;}}
  search.addEventListener('input',renderNav);search.addEventListener('keydown',(event)=>{if(event.key==='Enter'&&filteredPages()[0])select(filteredPages()[0].id);});mobileNav.addEventListener('change',()=>select(mobileNav.value));document.querySelector('#helpy-refresh').addEventListener('click',()=>load(true));document.querySelectorAll('[data-helpy-jump]').forEach((button)=>button.addEventListener('click',()=>select(button.dataset.helpyJump)));document.addEventListener('keydown',(event)=>{if(event.key==='/'&&!/input|textarea|select/i.test(document.activeElement?.tagName||'')){event.preventDefault();search.focus();}if(event.key==='Escape'&&document.activeElement===search){search.value='';search.blur();renderNav();}});
  const dialog=document.querySelector('#helpy-image-dialog');dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',(event)=>{if(event.target===dialog)dialog.close();});load(false);
})();
