(() => {
  'use strict';
  const rail=document.querySelector('#preview-rail');const header=document.querySelector('#preview-header');const content=document.querySelector('#preview-content');const toast=document.querySelector('#preview-toast');let model;let active='';
  const esc=(value)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function notify(label){toast.textContent=`${label} is demonstrated only. Download Dragonwilds Sync to perform real operations.`;toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove('show'),3200);}
  function select(id){const appy=model.appys.find((item)=>item.id===id)||model.appys[0];active=appy.id;history.replaceState(null,'',`#${encodeURIComponent(active)}`);render();}
  function render(){rail.innerHTML=`<div class="preview-rail-brand"><img src="assets/application-icon.png" alt=""><div><strong>Appys</strong><small>Explore the flow</small></div></div>${model.appys.map((appy,index)=>`<button type="button" class="${appy.id===active?'active':''}" data-appy="${esc(appy.id)}"><b>${String(index+1).padStart(2,'0')}</b><span>${esc(appy.label)}</span></button>`).join('')}`;rail.querySelectorAll('[data-appy]').forEach((button)=>button.addEventListener('click',()=>select(button.dataset.appy)));const appy=model.appys.find((item)=>item.id===active)||model.appys[0];header.innerHTML=`<div><div class="eyebrow">${esc(appy.kicker)}</div><h2>${esc(appy.title)}</h2><p>${esc(appy.description)}</p></div><span class="preview-context">Preview Profile / ${esc(appy.label)}</span>`;content.innerHTML=`<div class="preview-metrics">${appy.metrics.map((metric)=>`<div class="preview-metric"><small>${esc(metric.label)}</small><strong>${esc(metric.value)}</strong></div>`).join('')}</div><div class="preview-grid">${appy.cards.map((card)=>`<article class="preview-card"><div class="eyebrow">${esc(card.kicker)}</div><h3>${esc(card.title)}</h3><p>${esc(card.body)}</p><footer>${card.actions.map((action,index)=>`<button class="preview-action ${index===0?'primary':''}" type="button" data-demo="${esc(action)}">${esc(action)}</button>`).join('')}</footer></article>`).join('')}</div>`;content.querySelectorAll('[data-demo]').forEach((button)=>button.addEventListener('click',()=>notify(button.dataset.demo)));}
  fetch('assets/launcher-preview.json').then((response)=>{if(!response.ok)throw new Error(`Preview model returned ${response.status}`);return response.json();}).then((data)=>{model=data;select(decodeURIComponent(location.hash.slice(1))||model.appys[0].id);}).catch((error)=>{content.innerHTML=`<div class="preview-card"><h3>Preview unavailable</h3><p>${esc(error.message)}</p></div>`;});
})();
